version: '3.2'

volumes:
  artifactory-data:

services:
  artifactory-1:
    build: ./artifactory
    container_name: artifactory-1
    ports:
    - 8089:8081
    volumes:
    - artifactory-data:/var/opt/jfrog/artifactory
    environment:
    - DB_TYPE=mysql
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=root
    # Add extra Java options by uncommenting the following line
    #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
