version: '3.2'

volumes:
  sonar-data:
  artifactory-data:

services:
  artifactory:
    build: ./artifactory
    container_name: artifactory
    ports:
    - 8089:8081
    volumes:
    - artifactory-data:/var/opt/jfrog/artifactory
    environment:
    - DB_TYPE=mysql
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=root
    # Add extra Java options by uncommenting the following line
    #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
  mysql:
    restart: always
    image: mysql:5.7.23
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=artdb
    container_name: mysql
    volumes:
    - sonardb-data:/var/lib/mysql
