version: '3.2'

volumes:
  jenkins-home:
  sonardb-data:
  sonar-data:
  artifactory-data:

services:
  jenkins:
    image: aanorbel/jenkins-docker
    build: ./jenkins
    restart: always
    ports:
    - 8080:8080
    volumes:
    - jenkins-home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
  artifactory:
    build: ./artifactory
    container_name: artifactory
    ports:
    - 8089:8081
    volumes:
    - artifactory-data:/var/opt/jfrog/artifactory
    environment:
    - DB_TYPE=mysql
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=sonar
    - DB_PASSWORD=sonar
    # Add extra Java options by uncommenting the following line
    #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
  sonardb:
    restart: always
    image: mysql:5.7.23
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=sonar
    - MYSQL_DATABASE=sonar
    - MYSQL_USER=sonar
    - MYSQL_PASSWORD=sonar
    container_name: sonardb
    volumes:
    - sonardb-data:/var/lib/mysql
  sonar:
    image: sonarqube:lts-alpine
    restart: always
    ports:
    - 19000:9000
    - 19092:9092
    depends_on:
    - sonardb
    environment:
    - SONARQUBE_JDBC_URL=jdbc:mysql://sonardb:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    container_name: sonar
    volumes:
    - sonar-data:/opt/sonarqube/data
