version: '3.2'

volumes:
  jenkins-home:

services:
  jenkins:
    image: localhost:5000/jenkins-docker
    build: .
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
  artifactory:
    build: ./artifactory
    container_name: artifactory
    ports:
     - 8089:8081
#    volumes:
#     - ./artifactory:/var/opt/jfrog/artifactory
    environment:
     - DB_TYPE=mysql
     - DB_HOST=192.168.99.100
     - DB_PORT=33066
     - DB_USER=root
     - DB_PASSWORD=syncope
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
 sonardb:
    restart: always
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=sonar
     - MYSQL_DATABASE=sonar
     - MYSQL_USER=sonar
     - MYSQL_PASSWORD=sonar
    container_name: sonardb
    volumes:
      - sonardb-data:/var/lib/mysql
  sonar:
    image: sonarqube:lts-alpine
    restart: always
    ports:
     - "19000:9000"
     - "19092:9092"
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:mysql://sonardb:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
    container_name: sonar
    volumes:
      - sonar-data:/opt/sonarqube/data
