version: '3.2'

volumes:
  jenkins-home:

services:
  jenkins:
    image: aanorbel/jenkins-docker
    build: ./jenkins
    restart: always
    ports:
    - 8090:8080
    environment:
    - http_proxy: 81.168.153.152
    - https_proxy: 81.169.153.152
    volumes:
    - jenkins-home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
